from rest_framework.routers import DefaultRouter
from django.urls import include, path
from .views import ConversationViewSet, MessageViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'conversations', ConversationViewSet)
router.register(r'messages', MessageViewSet)

urlpatterns = [
    # All URLs generated by the router will be under 'api/v1/chats/'
    path('', include(router.urls)),
]
