from rest_framework.routers import DefaultRouter
from django.urls import include, path
from .views import ConversationViewSet, MessageViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'conversations', ConversationViewSet, basename='conversation')
router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    # All URLs generated by the router will be under this path
    path('', include(router.urls)),
]
